version: "3.8"
services:
    ptrader-backend:
        image: ptrader-backend
        build: ./backend
        secrets:
            - db_password
            - cert
            - key
            - vapid_key_txt
            - vapid_public_key_txt
        ports:
            - 8000:8000

    ptrader-frontend:
        image: ptrader-frontend
        build: ./frontend
        secrets:
            # - db_password
            - cert
            - key
        environment:
            - NODE_ENV=production
        ports:
            - 8001:8001
secrets:
    db_password:
        external: true
    cert:
        external: true
    key:
        external: true
    vapid_key_txt:
        external: true
    vapid_public_key_txt:
        external: true