version: "3.8"
services:
    ptrader-backend:
        image: ptrader-backend
        build: ./backend
        environment:
            - DATABASE_HOSTNAME=server
            - WORKER=ptrader-worker
        secrets:
            - mongo_password
            - cert
            - key
            - vapid_key_txt
            - vapid_public_key_txt
        ports:
            - 8000:8000
    
    ptrader-worker:
        image: ptrader-worker
        build:
            context: ./backend/
            dockerfile: worker.Dockerfile
        environment:
            - DATABASE_HOSTNAME=server
        secrets:
            - mongo_password
            - cert
            - key
            - vapid_key_txt
            - vapid_public_key_txt

    ptrader-frontend:
        image: ptrader-frontend
        build: ./frontend
        secrets:
            # - db_password
            - cert
            - key
        environment:
            - NODE_ENV=production
        ports:
            - 8001:8001
        volumes:
            - "./secrets:/app/secrets"
secrets:
    mongo_password:
        external: true
    cert:
        external: true
    key:
        external: true
    vapid_key_txt:
        external: true
    vapid_public_key_txt:
        external: true
