version: "3.8"
services:
    ptrader-backend:
        image: ptrader-backend
        build: ./backend
        environment:
            - DATABASE_HOSTNAME=mongo
            - WORKER=ptrader-worker
        secrets:
            - mongo_password
            - cert
            - key
            - vapid_key_txt
            - vapid_public_key_txt
        ports:
            - 8000:8000
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"    
    ptrader-worker:
        image: ptrader-worker
        build:
            context: ./backend/
            dockerfile: worker.Dockerfile
        environment:
            - DATABASE_HOSTNAME=mongo
            - AI=ptrader-ai
        secrets:
            - mongo_password
            - cert
            - key
            - vapid_key_txt
            - vapid_public_key_txt
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"
    ptrader-ai:
        image: ptrader-ai
        build:
            context: ./backend/
            dockerfile: ai.Dockerfile
        ports:
            - 8003:8003
        volumes:
            - ./models:/usr/models/
        secrets:
            - mongo_password
            - cert
            - key
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"
    ptrader-frontend:
        image: ptrader-frontend
        build: ./frontend
        secrets:
            # - db_password
            - cert
            - key
        environment:
            - NODE_ENV=production
        ports:
            - 8001:8001
        volumes:
            - "./secrets:/app/secrets"
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
        ports:
            - 27017:27017
        volumes:
            - mongo_mongodb:/data/db
        secrets:
            - mongo_username
            - mongo_password
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"
secrets:
    mongo_username:
        external: true
    mongo_password:
        external: true
    cert:
        external: true
    key:
        external: true
    vapid_key_txt:
        external: true
    vapid_public_key_txt:
        external: true

volumes:
    mongo_mongodb:
        external: true
